spring:
  profiles:
    active: local

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  level:
    root: info
    sql: error
    jdbc: off
    jdbc.sqlonly: debug
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace

server:
  servlet:
    encoding:
      force-response: true


---
# 로컬
spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/test; #메모리
    #url: jdbc:h2:file:./memoryDb #상대경로 파일저장(memoryDb.mv.db)
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 8080